
import { Language, TranslationStrings } from './types';

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  [Language.ENGLISH]: {
    subjectPrefix: 'QUOTE',
    subjectMiddle: 'QUOTE REQUEST',
    salutation: 'Dear',
    intro: 'please find attached the requested quotation.',
    delivery: 'Delivery time: {days} working days from your order confirmation.',
    decision: 'You can communicate your decision through the following link:',
    linkText: 'ACCEPT or REJECT THE QUOTE',
    feedback: 'Your feedback, even in case of rejection, is very important to us in order to constantly analyze and improve the quality of our proposals.',
    questions: "If you have any questions, please don't hesitate to contact us.",
    closing: 'Wishing you a good day and looking forward to hearing from you.',
    kindRegards: 'Kind regards,',
    labelRecipient: 'Recipient Name',
    labelEmailTo: 'Email To',
    labelQuoteId: 'Quote ID',
    labelSubject: 'Subject',
    labelService: 'Service',
    labelLanguages: 'Languages',
    labelAmount: 'Amount',
    labelDeliveryDays: 'Delivery Days',
    labelCc: 'Cc',
    placeholderRecipient: 'e.g. Maria',
    placeholderEmail: 'client@email.com',
    placeholderSubject: 'Project name...',
    placeholderLanguages: 'e.g. EN-IT',
    placeholderAmount: 'e.g. 1.250€',
    responseAccept: 'I ACCEPT THE QUOTE',
    responseReject: 'I REJECT THE QUOTE',
    responseReasonLabel: 'Reason for rejection',
    responseDetailsLabel: 'Details',
    decisionPageTitle: 'Take a decision regarding the quote',
    btnAcceptQuote: 'Accept quote',
    btnRejectQuote: 'Reject quote',
    rejectionReasonsTitle: 'Select the reason for rejection:',
    rejectionReasonTooLong: 'Delivery time is too long',
    rejectionReasonPrice: 'Price is slightly higher than another supplier',
    rejectionReasonBudget: 'Amount is out of budget',
    confirmAcceptTitle: 'Confirm Acceptance',
    confirmAcceptBody: 'Are you sure you want to accept this quote? This will prepare the confirmation email for the DEMA team.',
    confirmAcceptAction: 'Yes, I confirm acceptance',
    confirmSendTitle: 'Send Response',
    confirmSendBody: 'You are about to send your response. The email will open in your mail client.',
    confirmSendAction: 'Send Email',
    sentTitle: 'Response prepared!',
    sentBody: 'The response email has been opened in your default mail client. Please check and press send to complete the process.',
    btnEditResponse: 'Modify response',
    cancelAction: 'Cancel',
    attentionWarning: 'Attention! This action cannot be undone.'
  },
  [Language.ITALIAN]: {
    subjectPrefix: 'PREVENTIVO',
    subjectMiddle: 'RICHIESTA PREVENTIVO',
    salutation: 'Gentile',
    intro: 'in allegato trovi il preventivo richiesto.',
    delivery: 'Tempi di consegna: {days} giorni lavorativi dalla conferma d’ordine.',
    decision: 'Puoi comunicare la tua decisione tramite il seguente link:',
    linkText: 'ACCETTA o RIFIUTA IL PREVENTIVO',
    feedback: 'Il tuo feedback, anche in caso di rifiuto, è molto importante per noi per analizzare e migliorare costantemente la qualità delle nostre proposte.',
    questions: 'Se hai domande, non esitare a contattarci.',
    closing: 'Ti auguriamo una buona giornata e restiamo in attesa di un tuo riscontro.',
    kindRegards: 'Cordiali saluti,',
    labelRecipient: 'Nome Destinatario',
    labelEmailTo: 'Email Destinatario',
    labelQuoteId: 'ID Preventivo',
    labelSubject: 'Oggetto',
    labelService: 'Servizio',
    labelLanguages: 'Lingue',
    labelAmount: 'Importo',
    labelDeliveryDays: 'Giorni di Consegna',
    labelCc: 'Cc',
    placeholderRecipient: 'es. Maria',
    placeholderEmail: 'cliente@email.com',
    placeholderSubject: 'Nome progetto...',
    placeholderLanguages: 'es. EN-IT',
    placeholderAmount: 'es. 1.250€',
    responseAccept: 'ACCETTO IL PREVENTIVO',
    responseReject: 'RIFIUTO IL PREVENTIVO',
    responseReasonLabel: 'Motivo del rifiuto',
    responseDetailsLabel: 'Dettagli',
    decisionPageTitle: 'Prendi una decisione in merito al preventivo',
    btnAcceptQuote: 'Accetta preventivo',
    btnRejectQuote: 'Rifiuta preventivo',
    rejectionReasonsTitle: 'Seleziona il motivo del rifiuto:',
    rejectionReasonTooLong: 'Tempi troppo lunghi',
    rejectionReasonPrice: 'Prezzo poco più alto di un altro fornitore',
    rejectionReasonBudget: 'Importo fuori budget',
    confirmAcceptTitle: 'Conferma Accettazione',
    confirmAcceptBody: 'Sei sicuro di voler accettare questo preventivo? Questa operazione preparerà l\'email di conferma per il team DEMA.',
    confirmAcceptAction: 'Sì, confermo l\'accettazione',
    confirmSendTitle: 'Invia Risposta',
    confirmSendBody: 'Stai per inviare la tua risposta. L\'email verrà aperta nel tuo client di posta.',
    confirmSendAction: 'Invia Email',
    sentTitle: 'Risposta preparata!',
    sentBody: 'L\'email di risposta è stata aperta nel tuo client di posta predefinito. Controlla e premi invio per completare l\'operazione.',
    btnEditResponse: 'Modifica risposta',
    cancelAction: 'Annulla',
    attentionWarning: 'Attenzione! Questa azione non può essere annullata.'
  },
  [Language.SPANISH]: {
    subjectPrefix: 'PRESUPUESTO',
    subjectMiddle: 'SOLICITUD DE PRESUPUESTO',
    salutation: 'Estimado/a',
    intro: 'adjunto encontrará el presupuesto solicitado.',
    delivery: 'Plazo de entrega: {days} días laborables a partir de la confirmación del pedido.',
    decision: 'Puede comunicar su decisión a través del siguiente enlace:',
    linkText: 'ACEPTAR o RECHAZAR EL PRESUPUESTO',
    feedback: 'Sus comentarios, incluso en caso de rechazo, son muy importantes para nosotros para analizar y mejorar constantemente la calidad de nuestras propuestas.',
    questions: 'Si tiene alguna pregunta, no dude en ponerse en contacto con nosotros.',
    closing: 'Le deseamos un buen día y esperamos tener noticias suyas pronto.',
    kindRegards: 'Atentamente,',
    labelRecipient: 'Nombre del Destinatario',
    labelEmailTo: 'Correo Electrónico',
    labelQuoteId: 'ID del Presupuesto',
    labelSubject: 'Asunto',
    labelService: 'Servicio',
    labelLanguages: 'Idiomas',
    labelAmount: 'Importe',
    labelDeliveryDays: 'Días de Entrega',
    labelCc: 'Cc',
    placeholderRecipient: 'p. ej. María',
    placeholderEmail: 'cliente@email.com',
    placeholderSubject: 'Nombre del proyecto...',
    placeholderLanguages: 'p. ej. EN-IT',
    placeholderAmount: 'p. ej. 1.250€',
    responseAccept: 'ACEPTO EL PRESUPUESTO',
    responseReject: 'RECHAZO EL PRESUPUESTO',
    responseReasonLabel: 'Motivo del rechazo',
    responseDetailsLabel: 'Detalles',
    decisionPageTitle: 'Tome una decisión sobre el presupuesto',
    btnAcceptQuote: 'Aceptar presupuesto',
    btnRejectQuote: 'Rechazar presupuesto',
    rejectionReasonsTitle: 'Seleccione el motivo del rechazo:',
    rejectionReasonTooLong: 'Plazo de entrega demasiado largo',
    rejectionReasonPrice: 'Precio ligeramente superior al de otro proveedor',
    rejectionReasonBudget: 'El importe se sale del presupuesto',
    confirmAcceptTitle: 'Confirmar Aceptación',
    confirmAcceptBody: '¿Está seguro de que desea aceptar este presupuesto? Esto preparará el correo de confirmación para el equipo de DEMA.',
    confirmAcceptAction: 'Sí, confirmo la aceptación',
    confirmSendTitle: 'Enviar Respuesta',
    confirmSendBody: 'Está a punto de enviar su respuesta. El correo se abrirá en su cliente de correo.',
    confirmSendAction: 'Enviar Correo',
    sentTitle: '¡Respuesta preparada!',
    sentBody: 'El correo de respuesta se ha abierto en su cliente de correo predeterminado. Por favor, revíselo y pulse enviar para completar el proceso.',
    btnEditResponse: 'Modificar respuesta',
    cancelAction: 'Cancelar',
    attentionWarning: '¡Atención! Esta acción no se puede deshacer.'
  },
  [Language.CATALAN]: {
    subjectPrefix: 'PRESSUPOST',
    subjectMiddle: 'SOL·LICITUD DE PRESSUPOST',
    salutation: 'Benvolgut/da',
    intro: 'adjunt trobareu el pressupost sol·licitat.',
    delivery: 'Termini de lliurament: {days} dies laborables des de la confirmació de la comanda.',
    decision: 'Podeu comunicar la vostra decisió a través del següent enllaç:',
    linkText: 'ACCEPTAR o REBUTJAR EL PRESSUPOST',
    feedback: 'Els vostres comentaris, fins i tot en cas de rebuig, són molt importants per a nosaltres per analitzar i millorar costantment la qualitat de les nostres propostes.',
    questions: 'Si teniu cap pregunta, no dubteu a posar-vos en contacte amb nosaltres.',
    closing: 'Us desitgem un bon dia i esperem tenir notícies vostres aviat.',
    kindRegards: 'Cordialment,',
    labelRecipient: 'Nom del Destinatari',
    labelEmailTo: 'Correu Electrònic',
    labelQuoteId: 'ID del Pressupost',
    labelSubject: 'Assumpte',
    labelService: 'Servei',
    labelLanguages: 'Idiomes',
    labelAmount: 'Import',
    labelDeliveryDays: 'Dies de Lliurament',
    labelCc: 'Cc',
    placeholderRecipient: 'p. ex. Maria',
    placeholderEmail: 'client@email.com',
    placeholderSubject: 'Nom del projecte...',
    placeholderLanguages: 'p. ex. EN-IT',
    placeholderAmount: 'p. ex. 1.250€',
    responseAccept: 'ACCEPTO EL PRESSUPOST',
    responseReject: 'REBUTJO EL PRESSUPOST',
    responseReasonLabel: 'Motiu del rebuig',
    responseDetailsLabel: 'Detalls',
    decisionPageTitle: 'Preneu una decisió sobre il pressupost',
    btnAcceptQuote: 'Acceptar pressupost',
    btnRejectQuote: 'Rebutjar pressupost',
    rejectionReasonsTitle: 'Seleccioneu il motiu del rebuig:',
    rejectionReasonTooLong: 'Termini de lliurament massa llarg',
    rejectionReasonPrice: 'Preu lleugerament superior al d\'un altre proveïdor',
    rejectionReasonBudget: 'L\'import surt del pressupost',
    confirmAcceptTitle: 'Confirmar Acceptació',
    confirmAcceptBody: 'Esteu segur que voleu acceptar aquest pressupost? Això prepararà il correu de confirmació per a l\'equip de DEMA.',
    confirmAcceptAction: 'Sí, confirmo l\'acceptazione',
    confirmSendTitle: 'Enviar Resposta',
    confirmSendBody: 'Esteu a punt d\'enviar la vostra resposta. Il correu s\'obrirà al vostre client de correu.',
    confirmSendAction: 'Enviar Correu',
    sentTitle: 'Resposta preparada!',
    sentBody: 'Il correu de resposta s\'ha obert al vostre client de correu predeterminat. Si us plau, reviseu-lo i premeu enviar per completar il procés.',
    btnEditResponse: 'Modificar resposta',
    cancelAction: 'Cancel·lar',
    attentionWarning: 'Atenció! Aquesta acció no es pot desfer.'
  },
  [Language.GERMAN]: {
    subjectPrefix: 'ANGEBOT',
    subjectMiddle: 'ANGEBOTSANFRAGE',
    salutation: 'Guten Tag',
    intro: 'anbei erhalten Sie das gewünschte Angebot.',
    delivery: 'Lieferzeit: {days} Werktage ab Ihrer Auftragsbestätigung.',
    decision: 'Sie können uns Ihre Entscheidung über den folgenden Link mitteilen:',
    linkText: 'ANGEBOT ANNEHMEN oder ABLEHNEN',
    feedback: 'Ihr Feedback ist uns sehr wichtig, auch im Falle einer Ablehnung, um die Qualität unserer Angebote ständig zu analysieren und zu verbessern.',
    questions: 'Falls Sie Fragen haben, zögern Sie bitte nicht, uns zu kontaktieren.',
    closing: 'Wir wünschen Ihnen einen schönen Tag und freuen uns darauf, von Ihnen zu hören.',
    kindRegards: 'Mit freundlichen Grüßen,',
    labelRecipient: 'Name des Empfängers',
    labelEmailTo: 'E-Mail-Adresse',
    labelQuoteId: 'Angebots-ID',
    labelSubject: 'Betreff',
    labelService: 'Dienstleistung',
    labelLanguages: 'Sprachen',
    labelAmount: 'Betrag',
    labelDeliveryDays: 'Liefertage',
    labelCc: 'Cc',
    placeholderRecipient: 'z.B. Maria',
    placeholderEmail: 'kunde@email.de',
    placeholderSubject: 'Projektname...',
    placeholderLanguages: 'z.B. EN-IT',
    placeholderAmount: 'z.B. 1.250€',
    responseAccept: 'ICH NEHME DAS ANGEBOT AN',
    responseReject: 'ICH LEHNE DAS ANGEBOT AB',
    responseReasonLabel: 'Grund für die Ablehnung',
    responseDetailsLabel: 'Details',
    decisionPageTitle: 'Treffen Sie eine Entscheidung zum Angebot',
    btnAcceptQuote: 'Angebot annehmen',
    btnRejectQuote: 'Angebot ablehnen',
    rejectionReasonsTitle: 'Wählen Sie den Grund für die Ablehnung:',
    rejectionReasonTooLong: 'Lieferzeit ist zu lang',
    rejectionReasonPrice: 'Preis ist etwas höher als bei einem anderen Anbieter',
    rejectionReasonBudget: 'Betrag liegt außerhalb des Budgets',
    confirmAcceptTitle: 'Annahme bestätigen',
    confirmAcceptBody: 'Sind Sie sicher, dass Sie dieses Angebot annehmen möchten? Dies bereitet die Bestätigungs-E-Mail für das DEMA-Team vor.',
    confirmAcceptAction: 'Ja, ich bestätige die Annahme',
    confirmSendTitle: 'Antwort senden',
    confirmSendBody: 'Sie sind dabei, Ihre Antwort zu senden. Die E-Mail wird in Ihrem E-Mail-Programm geöffnet.',
    confirmSendAction: 'E-Mail senden',
    sentTitle: 'Antwort vorbereitet!',
    sentBody: 'Die Antwort-E-Mail wurde in Ihrem Standard-E-Mail-Programm geöffnet. Bitte prüfen Sie diese und drücken Sie auf Senden, um den Vorgang abzuschließen.',
    btnEditResponse: 'Antwort ändern',
    cancelAction: 'Abbrechen',
    attentionWarning: 'Achtung! Diese Aktion kann nicht rückgängig gemacht werden.'
  },
  [Language.FRENCH]: {
    subjectPrefix: 'DEVIS',
    subjectMiddle: 'DEMANDE DE DEVIS',
    salutation: 'Madame, Monsieur',
    intro: 'veuillez trouver ci-joint le devis demandé.',
    delivery: 'Délai de livraison : {days} jours ouvrables à compter de la confirmation de votre commande.',
    decision: 'Vous pouvez nous faire part de votre décision via le lien suivant :',
    linkText: 'ACCEPTER ou REFUSER LE DEVIS',
    feedback: 'Votre avis, même en cas de refus, est très important pour nous afin d’analyser et d’améliorer constamment la qualité de nos propositions.',
    questions: 'Si vous avez des questions, n’hésitez pas à nous contacter.',
    closing: 'En vous souhaitant une excellente journée, dans l’attente de votre réponse.',
    kindRegards: 'Cordialement,',
    labelRecipient: 'Nom du Destinataire',
    labelEmailTo: 'Adresse E-mail',
    labelQuoteId: 'ID du Devis',
    labelSubject: 'Objet',
    labelService: 'Service',
    labelLanguages: 'Langues',
    labelAmount: 'Montant',
    labelDeliveryDays: 'Jours de Livraison',
    labelCc: 'Cc',
    placeholderRecipient: 'ex. Maria',
    placeholderEmail: 'client@email.com',
    placeholderSubject: 'Nom du projet...',
    placeholderLanguages: 'ex. EN-IT',
    placeholderAmount: 'ex. 1.250€',
    responseAccept: 'J\'ACCEPTE LE DEVIS',
    responseReject: 'JE REFUSE LE DEVIS',
    responseReasonLabel: 'Motif du refus',
    responseDetailsLabel: 'Détails',
    decisionPageTitle: 'Prenez une decisione concernant le devis',
    btnAcceptQuote: 'Accepter le devis',
    btnRejectQuote: 'Refuser le devis',
    rejectionReasonsTitle: 'Sélectionnez le motif du refus :',
    rejectionReasonTooLong: 'Délai de livraison trop long',
    rejectionReasonPrice: 'Le prix est légèrement plus élevé qu’un altro fournisseur',
    rejectionReasonBudget: 'Le montant est hors budget',
    confirmAcceptTitle: 'Confirmer l\'acceptation',
    confirmAcceptBody: 'Êtes-vous sûr de vouloir accepter ce devis ? Cela préparera l\'e-mail de confirmation pour l\'équipe DEMA.',
    confirmAcceptAction: 'Oui, je confirme l\'acceptation',
    confirmSendTitle: 'Envoyer la réponse',
    confirmSendBody: 'Vous êtes sur le point d\'envoyer votre réponse. L\'e-mail s\'ouvrira dans votre client de messagerie.',
    confirmSendAction: 'Envoyer l\'e-mail',
    sentTitle: 'Réponse préparée !',
    sentBody: 'L\'e-mail de réponse a été ouvert dans votre client de messagerie par défaut. Veuillez vérifier et appuyer sur envoyer pour terminer le processus.',
    btnEditResponse: 'Modifier la réponse',
    cancelAction: 'Annuler',
    attentionWarning: 'Attention ! Cette action est irréversible.'
  }
};
